### PR TITLE
Index

### LINKED ISSUE #207: Add index entries
Add `\index{}` wherever appropriate.

### PR DESCRIPTION
**Pull request by emilyriederer**
Not completed but opening a PR to start working on the index. Here's a screenshot current as-of when I'm posting this. I welcome any feedback or critiques. 

How I generally am thinking about this is to use the index to help readers find information that they couldn't find elsewhere. So, I am focused less on the keywords that are already in the recipe titles and table of contents and more on the use case of "Oh I remember somewhere they mentioned this specific package or chunk option -- how did that work again"? For that reason, I put more effort into indexing packages / functions / options / etc.

Thanks!

Closes #207 
image

### CODE REVIEW

**Comment by cderv** [comment]
Awesome ! How do you want the review to be ? Like double check you did not forget index placement or either adding more index word maybe ?

**Comment by emilyriederer** [comment]
That's a good question on the review! I know there's definitely no good way to "check" that things aren't missing, but I guess it's maybe worth just thinking through things a reader might be trying to remember and see if it seems usable / navigable? I can always go back in and re-arrange if it seems hard to use. 

The other thing that I *think* I have fixed now but appreciate another pair of eyes is small accidental fragmentations. For example, for a while I had some entries under `chunk option` and some under `chunk options` by mistake. I hope I have caught these by now but it's something to keep an eye out for. 

I've now pushed all chapters. Here is a screenshot of the index including everything but Ch15. (For some reason I am having trouble with the Asymptote engine so I have to temporarily delete that one when I make the PDF until I can fix that. The files is as it should be in the PR, though!)

image
image
image

**Comment by cderv** [comment]
> For some reason I am having trouble with the Asymptote engine so I have to temporarily delete that one when I make the PDF until I can fix that. The files is as it should be in the PR, though!

Oh yeah ! I should have warned you as I am also a windows user. I already struggle with Asymptote on windows. You need to install it and make it available in the PATH so that it can compile.

**Comment by emilyriederer** [comment]
Oh, thanks @cderv! My problems is actually slightly different. I can find Asymptote and use it interactively, but when I run `make pdf`, I get the interactive pop-up version of the output and the render fails with this message:

```
freeglut (/Asymptote/asy): fgPlatformInitialize: CreateDC failed, Screen size info may be incorrect
This is likely caused by a bad '-display' parameter
Quitting from lines 5746-5764 (rmarkdown-cookbook.Rmd)
Error in engine(options) : Failed to compile the asy chunk 
```

Full version is in the screenshot:

image

Essentially, I seem to be seeing in a pop-up window what the book says is expected without the `settings.prc = false` setting; however that setting is turned on.

> In the `asy` chunk above, we used the setting `settings.prc = false`. Without this setting, Asymptote generates an interactive 3D graph when the output format is PDF. However, the interactive graph can only be viewed in Acrobat Reader. If you use Acrobat Reader, you can interact with the graph. For example, you can rotate the 3D surface in Figure \@ref(fig:elevation) with your mouse.

I haven't had a chance to dig into it very much, so I may try to do that today and perhaps just reinstall and see if that helps. If you have encountered this previously, though, definitely appreciate any tips!

**Comment by cderv** [comment]
Oh I retried and I have indeed the same issue... I thought I passed trough that... seems I don't. 😞 

I remember now this was blocking on this and then I rendered the pdf for review without evaluating this chunk. There is `eval` chunk option to deactivate this chunk on CI. So I used it by running this 😄 
```bash
CI=dummy make pdf
```
But I still encounter the font issue... not easy to build this PDF, and this is on purpose I recall. 😉

**Comment by emilyriederer** [comment]
I struggled with the fonts, too. At first, when I installed them, R could not find them even though other programs on my computer (e.g. Notepad) could. What I learned there is that initially I had installed them only to my "user space" on not the whole computer. I found that after I download the fonts, if I right click on them and choose "Install for all users" instead of "Install" then it worked for me.

**Comment by cderv** [comment]
Oh that was it. Install for all users. Windows is definitely not easy... Thank you ! 
I was missing Alegreya too it seems. Now it is ok.

**Pull request merged**
