### PR TITLE
Tag sections by difficulty level and reorder

### LINKED ISSUE #231: Tag sections by difficulty level, or reorder sections
One reviewer said:

> it would be nice if sections are tagged by level (e.g., beginner, intermediate, advanced). The tags especially catch and guide beginner's eye, and help those who skip reading preface.

I'm not sure if it's worth doing, but it sounds like a relatively simple task. I'll leave it to you to decide. I'd probably only indicate advanced topics instead of three levels, e.g., use an asterisk after section headers of advanced topics like `## Manipulate Markdown via Pandoc Lua filters (*)`.

---

One reviewer suggested us reorder sections in https://bookdown.org/yihui/rmarkdown-cookbook/chunk-options.html

> Sections with similar topics should be placed next to each other. Here is my suggestion:
> 
> * Use variables in chunk options 
> * Do not stop on error
> * Cache time-consuming code chunks 
> * Lazy-loading cached objects
> * Hide code, text output, messages, or plots
> * Hide everything from a chunk
> * Collapse text output blocks into source blocks
> * Reformat R source code
> * Programmatically generate content inside R Markdown
> * Remove leading hashes in text output
> * Multiple graphical output formats for the same plot
> * Post-process plots
> * High-quality graphics
> * Step-by-step plots with low-level plotting functions 
> * Customize the printing of objects in chunks
> * Option hooks

### PR DESCRIPTION
**Pull request by cderv**
Closes #231 

Following the idea of adding `(*)` at the end of the section title for advanced topic

### CODE REVIEW

**Comment by emilyriederer** [comment]
I think this will be very helpful! Should we add to `index.Rmd` "How to read this book" section to explain what the `*` means?

**Comment by yihui** [comment]
> Should we add to `index.Rmd` "How to read this book" section to explain what the `*` means?

Yes, of course.

**Comment by cderv** [comment]
Yes of course , I plan to to it. I should have start with that maybe ! 😅
If you want to chime in and add commits please do. (I think you can)

**Comment by cderv** [comment]
I went through the whole book now. 

* I find that we have some chapters that contains only advanced sections (like 12 and 13) - I added the (*) also on the chapter title AND all the sections in the chapter. We can only add to the sections maybe. 
* I hesitated to make chapter 14 as a full advanced chapter too. 
* At first, I regrouped the advanced section at the end of a chapter, but later on it did not make sense, so I stop. If you find we should put the moved sections back, please tell me. 
* I added a sentence in the How to read this book section in a middle of a paragraph. If you have a better sense on where to put it, feel free to do so. 

At last, the section I marked as advanced are based on my opinion and also my experience in helping and answering users about all these topics. @emilyriederer if you find I missed some, please tell me. @yihui, is this too much ? Did I miss some stuff you consider as pretty advanced as the author 😉 ?

**Pull request merged**
