### PR TITLE
Chapter 06 (LaTeX) Proofreading

### PR DESCRIPTION
**Pull request by emilyriederer**
Adding just a few trivial changes in chapter 6 to split long sentences. 

I'll also highlight that in the Rmd there is an unresolved question about turning a table to an image on line 231 (`<!-- This table may work better as a diagram? -->`). I think the resulting table looks fine, but I thought I would mention it.

### CODE REVIEW

**Comment by cderv** [comment]
@emilyriederer I did not find time this week to do chapter 5. I planned to do it this week end but I'Il let you do it as you're used to do it now 😅 

Is that OK with you? 

thank you!!!

**Comment by emilyriederer** [comment]
@cderv - happy to do it! I'll get it up either later today or tomorrow

**Comment by yihui** [comment]
Just to let you know, I'm going to take the next week off (I don't even remember when was the last time I took a break---feels like more than a year ago). After I merge the PR for Chap 5, I'll send the PDF to John so they can start production. You should have plenty of time to work on the index. In the meantime, if you find any other obvious problems in the manuscript, please feel free to fix them directly in the `master` branch (no need to do PRs). Thanks!

BTW, if you want to work on the PDF issues #210 (after we hear back from the copy editor), you may try to build the PDF on your computer now. It is probably not very straightforward (which is kind of intentional), so please let me know if you run into any problems. To be honest, it's not my favorite job to fix the PDF issues, because they require you to recompile the book over and over again, which is extremely boring and time-consuming... 😂

**Comment by emilyriederer** [comment]
Actually, the cookbook itself helped me debug a few of the problems to build the PDF! I hadn't done much with LaTeX package installation before and it taught me exactly the `tinytex` tricks I needed. I only have three remaining questions:

1. So far, I have mostly (see Q2) succeeded by running the line `Rscript --quiet _render.R "bookdown::pdf_book"` from the `makefile` in the terminal and can produce a PDF. Do the commands under `pdf` or `pdf2` produce the version that goes to the publisher? 

2. When I run that command as-is, I get the error: `Package fontspec Error: The font "Palatino" cannot be found.`. To test the rest of my system, I change the font in `index.Rmd` from Palantino to Palantino Linotype, but obviously I would need to use the precise font to check the formatting. Reading online, I read that I should install the `palatino` package; however, I have tried that and confirmed it is installed and yet it is still not found. Are there any other obvious things to try or packages to install? Otherwise, I can keep digging into it.

image

3. Is it fair to assume that floats should be independent across chapters? If that is an alright assumption, I was thinking it could be faster to iterate and check the formatting by rendering the book with fewer chapters.

**Comment by yihui** [comment]
@emilyriederer 

1. `make pdf`.

2. Sounds like you are on Windows? My bad. I should have considered using a font that's available on all platforms. Palatino is only available on macOS. I don't know how much difference there is between Palatino and Palatino Linotype. Perhaps you can randomly check a few pages in your full PDF and mine (the link is in one of my previous emails).

    I'm open to using other fonts. I used Alegreya in the **bookdown** book, which is freely available on Google Fonts. It feels a little scary at this point to change the main font (it could increase or decrease the number of pages by 30 or perhaps 50), but I have no objection to giving it a try. Do you have a few favorite fonts on https://fonts.google.com/?category=Serif,Display?

    BTW, the LaTeX package **palatino** only works for `pdflatex`. Our book uses `xelatex`, which uses fonts available in the OS.

3. Yes, you can assume independency. You can preview one chapter at a time by clicking the Knit button: https://bookdown.org/yihui/bookdown/preview-a-chapter.html But remember to (temporarily) make `bookdown::pdf_book` the default (i.e. first) output format in `_output.yml`.

**Comment by emilyriederer** [comment]
Thanks for the answers! That all makes sense. 

I don't have any favorites, persay, but the PDF you sent with Crimson Text looks good, and it is quite an advantage if the dimensions of that font are already very similar. Alegreya is also nice. I'm sorry to make you change just for my OS, though!

**Comment by cderv** [comment]
> I'm sorry to make you change just for my OS, though!

I am also on windows! 😉 @yihui you are outnumbered! 😆

**Comment by yihui** [comment]
Okay! Let's use Palatino Linotype! 😁 

Just kidding. I just changed the font to Crimson Text. If you download and install the font from Google Fonts, you should be able to compile to PDF now.

**Pull request merged**
